# Generated by Django 3.2.4 on 2021-06-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ad_insertPoints',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ad_url',
        ),
        migrations.AddField(
            model_name='task',
            name='ad_insertPoints1',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ad_insertPoints2',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ad_url1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ad_url2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
